services:
  lotto:
    build: .
    container_name: lotto
    restart: always
    ports:
      - "3004:5000"
    env_file:
      - path: ./.env
        required: false
    volumes:
      - ./lottery.db:/app/lottery.db
